language: perl
perl:
  - "5.8.1"
  - "5.8.9"
  - "5.8.9_thr"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.14.2_thr"
  - "5.16"
  - "5.16.2_thr"
  - "5.18"
  - "5.18.2_thr"
  - "5.19"
before_install:
  - "source devel.travis/travis-perlbrew"
  - "perlbrew install-cpanm -f"
  - "perl -V"
install:
  - "cpanm -n Test::Modern"
  - "perl -e'system cpanm => ($] < 5.014) ? q(Devel::Declare) : q(Keyword::Simple)'"
script:
  - prove -Ilib t
notifications:
  irc:
    channels:
      - "irc.perl.org#moops"
    on_success: change
